{{- if and .Values.app.name .Values }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.app.name }}
spec:
  selector:
    app: {{ .Values.app.name }}
{{- end }}