{{- if and .Values.app .Values.app.name }}  # Check if .Values.app and .Values.app.name are set
apiVersion: networking.istio.io/v1alpha3
kind: Sidecar
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.app.name }}
spec:
  workloadSelector:
    labels:
      app: {{ .Values.app.name }}
  egress:
    - bind: unix://@istio-proxy-egress.sock
      captureMode: NONE
      hosts:
        {{- range .Values.app_dependencies }}
          - "{{ . }}/*"
        {{- end }}
{{- end }}  # End the if block
