{{- if and .Values.app .Values.app.name }}  # Check if .Values.app and .Values.app.name are set
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.app.name }}
spec:
  selector:
    app: {{ .Values.app.name }}
{{- end }}