{{- if and .Values.app .Values.app.name }}  # Check if .Values.app and .Values.app.name are set
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.app.name }}
{{- end }}